BEGIN TRANSACTION;
ALTER TABLE MODS 
	RENAME IsInstalled TO IsInstalledSteam;
ALTER TABLE MODS 
	ADD COLUMN IsInstalledEGS INTEGER NOT NULL DEFAULT 0;
ALTER TABLE MODS 
	ADD COLUMN ModVersion TEXT NOT NULL DEFAULT "";
COMMIT;