BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Collections" (
	"Id"	INTEGER NOT NULL,
	"CollectionName"	TEXT NOT NULL UNIQUE,
	"CollectionPath"	TEXT NOT NULL UNIQUE,
	"CollectionDescription"	TEXT NOT NULL,
	PRIMARY KEY("Id")
);
CREATE TABLE IF NOT EXISTS "Images" (
	"Id"	INTEGER NOT NULL,
	"ImagePath"	TEXT NOT NULL UNIQUE,
	"ImageDescription"	TEXT NOT NULL,
	"ImageThumbnailPath" TEXT NOT NULL, 
	"CollectionId"	INTEGER NOT NULL,
	FOREIGN KEY("CollectionId") REFERENCES "Collections"("Id") ON DELETE RESTRICT,
	PRIMARY KEY("Id")
);
CREATE TABLE IF NOT EXISTS "ImageTags" (
	"Id"	INTEGER NOT NULL,
	"ImageId"	INTEGER NOT NULL,
	"TagId"	INTEGER NOT NULL,
	FOREIGN KEY("ImageId") REFERENCES "Images"("Id") ON DELETE CASCADE,
	FOREIGN KEY("TagId") REFERENCES "Tags"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id")
);
COMMIT;
