BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS Livery (
	Id INTEGER PRIMARY KEY NOT NULL,
	NameTEXT NOT NULL,
	FilePath TEXT UNIQUE ON CONFLICT IGNORE,
	FileName TEXT  NOT NULL,
	DLCName	TEXT NOT NULL,
	Description	TEXT NOT NULL,
	Image	TEXT NOT NULL,
	Source	TEXT NOT NULL,
	LiveryType	TEXT NOT NULL,
	ReplaceName	TEXT NOT NULL,
	IsInstalled	INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS RadioStations (
        Id  INTEGER PRIMARY KEY NOT NULL,
        Url TEXT  NOT NULL,
        Route TEXT NOT NULL,
        Description TEXT NOT NULL
         );

		CREATE TABLE IF NOT EXISTS Routes (
				Id  INTEGER PRIMARY KEY NOT NULL,
				RouteName TEXT NOT NULL,
				RouteAbbrev TEXT NOT NULL UNIQUE ON CONFLICT IGNORE,
				RouteDescription  TEXT NOT NULL,
				RouteImagePath TEXT NOT NULL,
				ScenarioPlannerRouteName TEXT NUL NULL,
				ScenarioPlannerRouteString TEXT NOT NULL,
				DlcId INT,
				FOREIGN KEY("DlcId") REFERENCES "Dlcs" ON DELETE CASCADE
				);

		CREATE TABLE IF NOT EXISTS Dlcs (
				Id  INTEGER PRIMARY KEY NOT NULL,
				DlcName TEXT NOT NULL,
				DlcDescription TEXT NOT NULL,
				DlcImagePath TEXT NOT NULL,
				DilcSource TEXT NOT NULL
				);

CREATE TABLE IF NOT EXISTS `Liveries` (
	`Id`	INTEGER PRIMARY KEY NOT NULL,
	`LiveryName`	TEXT  NOT NULL,
	`FileName`	TEXT UNIQUE ON CONFLICT IGNORE,
	`LiveryDescription`	TEXT  NOT NULL,
	`LiveryImage`	TEXT  NOT NULL,
	`LiverySource`	TEXT  NOT NULL,
	`LiveryType`	TEXT  NOT NULL,
	RouteId INTEGER DEFAULT null,
	FOREIGN KEY("RouteId") REFERENCES "Routes" ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `LiverySets` (
	`Id`	INTEGER PRIMARY KEY NOT NULL,
	LiverySetName TEXT NOT NULL,
	`LiverySetDescription`	TEXT  NOT NULL,
	`RouteId`	INTEGER DEFAULT null,
	FOREIGN KEY("RouteId") REFERENCES "Routes" ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `LiveryLiverySet` (
	`Id`	INTEGER PRIMARY KEY NOT NULL,
	`LiverySetId`	INTEGER DEFAULT null,
	`LiveryId`	INTEGER DEFAULT null,
	FOREIGN KEY("LiverySetId") REFERENCES "LiverySets" ON DELETE CASCADE
	FOREIGN KEY("LiveryId") REFERENCES "Liveries" ON DELETE CASCADE
);

COMMIT;